from __future__ import annotations

from typing import Protocol

from .models import Block


class BlockRepositoryProtocol(Protocol):
    def get_all(self) -> list[Block]: ...
    def append(self, block: Block) -> None: ...
    def last(self) -> Block: ...
    def count(self) -> int: ...
