from __future__ import annotations

from typing import Protocol

from .models import Block, Transaction


class BlockRepositoryProtocol(Protocol):
    def get_all(self) -> list[Block]: ...
    def append(self, block: Block) -> None: ...
    def last(self) -> Block: ...
    def count(self) -> int: ...
    def replace_all(self, blocks: list[Block]) -> None: ...
    def save_confirmed_transactions(self, block_index: int, txs: list[Transaction]) -> None: ...
